# config.yml (New Version for Person Detection Focus)
app:
  project_root: "." # Assumes script runs from project root, or paths are relative to this file

rtsp:
  url: "rtsp://admin:qwerty13579@192.168.0.3:554/Streaming/Channels/102" # !!! REPLACE with your RTSP stream or 0 for webcam !!!
  # url: 0 # For webcam testing
  capture_resolution_width: 640 # Consider 1280x720 for lighter load
  capture_resolution_height: 480
  capture_fps: 15 # Desired capture/processing FPS. Camera should support this.
  reconnect_delay_seconds: 5

inference:
  model_path: "models/yolov8n.pt" # Path to your ONNX model
  confidence_threshold: 0.40 # Confidence for detecting a person
  # Ensure this class ID corresponds to "person" in your ONNX model
  # For COCO-trained models (like standard YOLO), 'person' is usually class ID 0.
  person_class_id: 0
  process_every_nth_frame: 1 # Process 1 out of N frames. 1 = process all.
  device: "cpu" # or "cuda:0" for GPU if ONNXRuntime-GPU & CUDA are set up

person_event_recording:
  enabled: true
  # Directory where person-triggered video clips will be saved.
  # Relative to project_root or absolute.
  output_directory: "person_clips"
  # How many seconds of frames to keep in a rolling buffer.
  # This buffer is used for pre-event recording and to ensure smooth clip transitions.
  # Should be at least pre_event_seconds + a small margin.
  frame_buffer_seconds: 8
  # How many seconds of video to include *before* a person is initially detected.
  pre_event_seconds: 3
  # If no person is detected for this many seconds, the current recording segment ends.
  post_event_timeout_seconds: 5
  # Clip FPS will be the same as rtsp.capture_fps.
  filename_prefix: "person" # e.g., person_20231027-153000.mp4

archive_maintenance: # Manages the 'person_event_recording.output_directory'
  enabled: true
  max_clip_age_days: 7             # Delete clips older than this many days.
  min_disk_free_gb_threshold: 5    # Minimum free disk space in GB to maintain.
  cleanup_interval_seconds: 3600   # How often to run cleanup (e.g., 1 hour).

logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR
  directory: "logs"
  filename: "person_detector.log"
  rotation_max_bytes: 10485760 # 10MB
  rotation_backup_count: 3

display: # For the cv2.imshow placeholder
  show_window: true
  window_name: "Person Detector - Live Feed"
  fps_display_interval: 1.0 # seconds, how often to update FPS display